#+TITLE: 颜色渐变 Color Ramp

* 颜色渐变节点 BVTK_Node_ColorRampType
** 节点详解
此节点的作用是定义一个颜色查找表（Lookup Table, LUT）。它本身不处理任何几何数据。

它的唯一功能是建立一个“数值 -> 颜色”的映射规则。例如，定义 0.0 对应蓝色，0.5 对应绿色，1.0 对应红色，并自动在这些颜色之间生成平滑的渐变。

*** 为什么需要这个节点？
~Color Mapper~ （颜色映射器）节点知道如何应用颜色，但它不知道具体要应用什么颜色。 ~Color Ramp~ 节点就是用来告诉 ~Color Mapper~ 颜色方案的。

它将抽象的标量数据（如 ~vtkElevationFilter~ 生成的 0.0 到 1.0 的值）转换成具体的视觉信息（颜色）。

*** 什么情况下要使用这个节点？
任何时候您需要使用 ~Color Mapper~ 节点进行标量数据着色时，都必须连接一个 ~Color Ramp~ 节点。

*** 使用这个节点的注意事项
1.  连接：此节点的 ~lookupTable~（查找表）输出端口必须连接到 ~Color Mapper~ 节点的 ~lookuptable~ 输入端口。
2.  颜色位置：在 ~elements~ 数组中，每个色标的 ~position~ 值（ ~[[R,G,B,A], position]~ 中的最后一个数字）都应在 0.0 到 1.0 的范围内。
3.  独立性：此节点本身没有可见输出。它必须与 ~Color Mapper~ 配合使用才能生效。

** 节点参数
- bl_idname: BVTK_Node_ColorRampType
- color: 任意三元组，如 ~[0.3, 0.3, 0.3]~
- custom_code: 默认为空，如 ~""~
- height: 任意数字，如 ~100.0~
- hide: 默认为 ~false~
- label: 默认为空，如 ~""~
- location: 任意二元组，如 ~[-234.5, 17.6]~
- width: 任意数字，如 ~200.0~
- show_preview: 默认为 ~false~
- show_options: 默认为 ~true~
- mute: 默认为 ~false~
- name: Color Ramp
- additional_properties: 额外属性, 包含 ~elements~ 数组。
- elements: (在 ~additional_properties~ 内部) 颜色元素数组。每个元素定义一个色标，格式为 ~[[R, G, B, A], position]~，其中 ~position~ 是 0.0 到 1.0 之间的一个值。
- cm_nr_values: 颜色表中的值的数量, 如 ~8~。
- cm_preset: 预设, 使用的预设颜色渐变名称，~custom~ 表示自定义。
- texture_name: 纹理名称, 关联的纹理名称，如 ~texture1~。

** 单个 Color Ramp 节点示例
#+begin_src json
{
    "additional_properties": {
        "elements": [
            [
                [
                    0.03921568766236305,
                    0.03921568766236305,
                    0.7058823704719543,
                    1.0
                ],
                0.05000000074505806
            ],
            [
                [
                    0.5529412031173706,
                    0.6901960968971252,
                    0.9960784316062927,
                    1.0
                ],
                0.42500001192092896
            ],
            [
                [
                    0.8666666746139526,
                    0.8666666746139526,
                    0.8666666746139526,
                    1.0
                ],
                0.5
            ],
            [
                [
                    0.9529411792755127,
                    0.5803921818733215,
                    0.4588235318660736,
                    1.0
                ],
                0.5972220301628113
            ],
            [
                [
                    0.7058823704719543,
                    0.03921568766236305,
                    0.0784313753247261,
                    1.0
                ],
                0.949999988079071
            ]
        ]
    },
    "bl_idname": "BVTK_Node_ColorRampType",
    "cm_nr_values": 8,
    "cm_preset": "custom",
    "color": [
        0.30000001192092896,
        0.30000001192092896,
        0.30000001192092896
    ],
    "custom_code": "",
    "height": 100.0,
    "hide": false,
    "label": "",
    "location": [
        -234.5421142578125,
        17.68448829650879
    ],
    "mute": false,
    "name": "Color Ramp",
    "show_options": true,
    "show_preview": false,
    "texture_name": "texture1",
    "width": 200.0
}
#+end_src
