#+TITLE: 高程过滤器 vtkElevationFilter

* 高程过滤器节点 VTKElevationFilterType
** 节点详解
此节点的主要作用是为输入的几何数据（如网格）的 *每个顶点* （Point）添加一个新的标量（Scalar）数据数组。
这个标量值是根据每个顶点在一条 *指定轴线* 上的位置计算出来的。这条轴线由 ~m_LowPoint~ 和 ~m_HighPoint~ 两个参数定义。

*** 为什么需要这个节点？
数据源（如 ~vtkConeSource~ 或 ~vtkSphereSource~）通常只生成几何信息（顶点的X, Y, Z坐标），但 *不包含* 与之关联的标量数据（如温度、压力、高度等）。

而后续的 ~Color Mapper~ （颜色映射器）节点 *必须* 依赖这些标量数据才能进行着色。 ~vtkElevationFilter~ 的作用就是 *生成* 这些必需的标量数据，充当了纯几何体和数据可视化（着色）之间的桥梁。

通常用于对一个集合模型根据物理形状、空间位置或者其他物理属性（冲量等等）进行可视化时，就应该使用这个节点。

*** 使用这个节点的注意事项
1.  轴线定义： ~m_LowPoint~ 和 ~m_HighPoint~ 是最重要的参数。它们定义的向量方向必须与您希望测量“高程”的方向一致。例如，要测量Z轴高度，应设置 ~m_LowPoint~ 为 ~[0, 0, -1]~ ， ~m_HighPoint~ 为 ~[0, 0, 1]~ 。
2.  标量范围： ~m_ScalarRange~ 默认是 ~[0.0, 1.0]~。这非常方便，因为它正好对应 ~Color Ramp~ 节点的标准输入范围。
3. 数据命名：此节点默认生成的标量数组名为 "Elevation"。在后续的 ~Color Mapper~ 节点中，您必须在 ~color_by~ 参数中选择 ~P_Elevation~ (P代表Point，即顶点数据)，才能正确地使用这个数据进行着色。
** 节点参数
- bl_idname: VTKElevationFilterType
- color: 任意三元组，如 ~[0.3, 0.3, 0.3]~
- custom_code: 默认为空，如 ~""~
- height: 任意数字，如 ~100.0~
- hide: 默认为 ~false~
- label: 默认为空，如 ~""~
- location: 任意二元组，如 ~[-250.0, 300.0]~
- width: 任意数字，如 ~200.0~
- show_preview: 默认为 ~false~
- show_options: 默认为 ~true~
- mute: 默认为 ~false~
- name: vtkElevationFilter
- m_ObjectName: 默认为空， ~""~
- m_LowPoint: 低点坐标, 定义计算高程向量的起点。高程标量是根据每个点投影到这个（LowPoint -> HighPoint）向量上的位置计算的。通常为 ~[0.0, 0.0, -1.0]~
- m_HighPoint: 高点坐标, 定义计算高程向量的终点。通常为 ~[0.0, 0.0, 1.0]~
- m_ScalarRange: 标量范围, 定义输出高程标量值的范围，例如 ~[0.0, 1.0]~ 。输入几何体上的点将被赋予这个范围内的一个值。

** 单个 vtkElevationFilter 节点示例
#+begin_src json
{
    "bl_idname": "VTKElevationFilterType",
    "color": [
        0.30000001192092896,
        0.30000001192092896,
        0.30000001192092896
    ],
    "custom_code": "",
    "height": 100.0,
    "hide": false,
    "label": "",
    "location": [
        -250.0,
        300.0
    ],
    "m_HighPoint": [
        0.0,
        0.0,
        1.0
    ],
    "m_LowPoint": [
        0.0,
        0.0,
        -1.0
    ],
    "m_ObjectName": "",
    "m_ScalarRange": [
        0.0,
        1.0
    ],
    "mute": false,
    "name": "vtkElevationFilter",
    "show_options": true,
    "show_preview": false,
    "width": 200.0
}
#+end_src
